//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationSetting
    {
        public int ConfigId { get; set; }
        public string ConfigValue { get; set; }
        public System.Guid ConfigValueKey { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ConfigEventDetail { get; set; }
        public string Email { get; set; }
        public string ConfigSummary { get; set; }
        public string ConfigAppEvent { get; set; }
        public string CcEmail { get; set; }
    }
}
