//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigurationSettingDetail
    {
        public int ConfigDetailId { get; set; }
        public System.Guid ConfigAppKey { get; set; }
        public string ParamName { get; set; }
        public string ParamValue { get; set; }
        public string AdditionalParamName { get; set; }
        public string AdditionalParamValue { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
