//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStream_BaseColumns_Mapping
    {
        public int BaseColumnMappingId { get; set; }
        public System.Guid BaseColumnMappingKey { get; set; }
        public System.Guid FileStreamKey { get; set; }
        public System.Guid BaseColumnKey { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
