//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStream_BaseColumns
    {
        public int BaseColumnId { get; set; }
        public System.Guid BaseColumnKey { get; set; }
        public string BaseColumnName { get; set; }
        public string BaseColumnDescription { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsEnrypted { get; set; }
        public Nullable<int> MandatoryCheck_Order { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
    }
}
