//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileStream_Types
    {
        public int FileStreamId { get; set; }
        public System.Guid FileStreamKey { get; set; }
        public string FileStreamExtension { get; set; }
        public string Description { get; set; }
        public bool IsActiveDownStream { get; set; }
        public bool IsActiveUpStream { get; set; }
        public bool IsDefaultDownStream { get; set; }
        public bool IsDefaultUpStream { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
