//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiraTicket_ColumnConfigurations
    {
        public int ColumnId { get; set; }
        public System.Guid ColumnKey { get; set; }
        public string ColumnName { get; set; }
        public bool IsEncrypted { get; set; }
        public bool IsExternal { get; set; }
        public bool IsActive { get; set; }
        public string JiraMapping { get; set; }
        public Nullable<int> ColumnType { get; set; }
    }
}
