//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiraTicketDetails
    {
        public int TicketDetailId { get; set; }
        public System.Guid TicketDetailKey { get; set; }
        public System.Guid TicketKey { get; set; }
        public Nullable<System.Guid> ColumnKey { get; set; }
        public string ColumnValue { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateTime { get; set; }
    }
}
