//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiraTickets
    {
        public int Ticketld { get; set; }
        public System.Guid TicketKey { get; set; }
        public string ReferenceId { get; set; }
        public string ReferenceURL { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateTime { get; set; }
        public string ClockSeq { get; set; }
        public string FileName { get; set; }
    }
}
