//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaycomEngineContext : DbContext
    {
        public PaycomEngineContext()
            : base("name=PaycomEngineContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FileStream_BaseColumns> FileStream_BaseColumns { get; set; }
        public virtual DbSet<FileStream_BaseColumns_Mapping> FileStream_BaseColumns_Mapping { get; set; }
        public virtual DbSet<FileStream_Types> FileStream_Types { get; set; }
        public virtual DbSet<PaycomData> PaycomData { get; set; }
        public virtual DbSet<PaycomData_History> PaycomData_History { get; set; }
        public virtual DbSet<ConfigurationActivity> ConfigurationActivity { get; set; }
        public virtual DbSet<PaycomData_Logs_Level1> PaycomData_Logs_Level1 { get; set; }
        public virtual DbSet<PaycomData_Logs_Level2> PaycomData_Logs_Level2 { get; set; }
        public virtual DbSet<ConfigurationSetting> ConfigurationSetting { get; set; }
        public virtual DbSet<ConfigurationSettingDetail> ConfigurationSettingDetail { get; set; }
        public virtual DbSet<JiraTicket_ColumnConfigurations> JiraTicket_ColumnConfigurations { get; set; }
        public virtual DbSet<JiraTicketDetails> JiraTicketDetails { get; set; }
        public virtual DbSet<JiraTickets> JiraTickets { get; set; }
        public virtual DbSet<PaycomData_MissingInfo> PaycomData_MissingInfo { get; set; }
        public virtual DbSet<PaycomData_Scrubbed> PaycomData_Scrubbed { get; set; }
    }
}
