//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaycomData_History
    {
        public int PaycomHistoryDataId { get; set; }
        public System.Guid PaycomHistoryDataKey { get; set; }
        public int PaycomDataId { get; set; }
        public System.Guid PaycomDataKey { get; set; }
        public string Employee_Code { get; set; }
        public string Employee_FirstName { get; set; }
        public string Employee_MiddleName { get; set; }
        public string Employee_LastName { get; set; }
        public string Department_Desc { get; set; }
        public string Tier_2_Desc { get; set; }
        public string Tier_3_Desc { get; set; }
        public string Employee_Status { get; set; }
        public string ClockSeq { get; set; }
        public string Hire_Date { get; set; }
        public string Termination_Date { get; set; }
        public string Rehire_Date { get; set; }
        public string PartTime_to_FullTime_Date { get; set; }
        public string Supervisor_Primary { get; set; }
        public string Last_Position_Change_Date { get; set; }
        public string City1 { get; set; }
        public string Country { get; set; }
        public string Currency { get; set; }
        public string City2 { get; set; }
        public string NTLogin { get; set; }
        public string Work_Email { get; set; }
        public string Position { get; set; }
        public string ManagerEmpID { get; set; }
        public string EntityName { get; set; }
        public string LineMgrEmailID { get; set; }
        public string Manager_NT_Login { get; set; }
        public Nullable<System.DateTime> DumpDate { get; set; }
        public string InitiatedBy { get; set; }
        public System.DateTime HistoryDumpDate { get; set; }
        public string Employee_Name { get; set; }
        public string FullTime_to_PartTime_Date { get; set; }
        public Nullable<System.DateTime> InsertionDate { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public string Certify_DSFlag { get; set; }
        public string Exchange_DSFlag { get; set; }
        public string WorkLocation { get; set; }
    }
}
