//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaycomData_MissingInfo
    {
        public int DataId { get; set; }
        public System.Guid DataKey { get; set; }
        public string ClockSeq { get; set; }
        public string Employee_Code { get; set; }
        public string NT_Login { get; set; }
        public string Work_Email { get; set; }
        public string Is_Processed { get; set; }
        public string CurrentJiraStatus { get; set; }
        public string JiraTicketReference { get; set; }
        public string JiraTicketURL { get; set; }
        public string InitiatedBy { get; set; }
        public Nullable<System.DateTime> InsertionDate { get; set; }
        public string InsertionFileName { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdationDate { get; set; }
        public string UpdationFileName { get; set; }
        public Nullable<int> UpdateCount { get; set; }
        public string IsActive { get; set; }
    }
}
