//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afiniti.Paycom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaycomData_Logs_Level2
    {
        public int ProcessRowLogId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string LogType { get; set; }
        public string LogStage { get; set; }
        public string FileName { get; set; }
        public string ColumnName { get; set; }
        public string LogDetail { get; set; }
    }
}
